#!/bin/sh

NAME=$1
TEMPLATE_DIR=$PWD/tests/templates/$2
TMP_DIR=$(mktemp -d)

trap 'rm -r -- "$TMP_DIR"' EXIT

mkdir $TMP_DIR/$NAME
cp $TEMPLATE_DIR/* $TMP_DIR/$NAME
tar -C $TMP_DIR -czf tests/data/$NAME.tar.gz $NAME
