name: tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Determine exact Python version
        run:
          echo "PYTHON_VERSION=$(python -c 'import platform; print(platform.python_version())')" >> $GITHUB_ENV
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python${{ matrix.python-version }}/site-packages
            ~/.local/bin
          key: ${{ runner.os }}-python${{ env.PYTHON_VERSION }}-${{ hashFiles('**/setup.cfg') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install_devel
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Test
        run: |
          make check test
